####################
# Codex Presence Cluster

type: custom:layout-card
layout: grid
gridcols: 25% auto
gridrows: auto
cards:
  # Person Picture, fades out when `not_home`
  - type: picture-entity
    gridcol: 1 / 2
    gridrow: 1 / 1
    entity: input_boolean.presence_codex
    show_name: false
    show_state: false
    state_image:
      'on': /local/people/detected_codex.png
      'off': /local/people/undetected_codex.png
    state_filter:
      'off': opacity(0.3)
    style: |
      ha-card {
        background: none;
        box-shadow: none;
      }

  # Person Specs
  - type: vertical-stack
    gridcol: 2 / 2
    gridrow: 1 / 1
    cards:
      # Display of Person State
      - type: markdown
        content: "{{ state_attr('device_tracker.phone_codex', 'friendly_name') }} is at {{states('device_tracker.phone_codex').replace('_',' ').title()}}"
        style: |
          ha-card {
            background: rgba(48, 50, 54, 0.25);
            border: 1px solid rgba(255, 255, 255, 0.4);
            text-align: center;
          }

          ha-markdown.markdown.no-header {
            padding: 3px;
          }

      # Display of Battery %
      - type: custom:bar-card
        entity: sensor.presence_battery_phone_codex
        color: '#DF6040'
        height: 20px
        icon: mdi:battery
        show_icon: true
        title_position: 'off'
        style: |
          ha-card {
            background: none;
            box-shadow: none;
          }