# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

alexa:
  smart_home:
api:
automation: !include_dir_merge_list config/automations
camera: !include config/cameras.yaml
cast:
  media_player:
    - host: 192.168.1.100
cover: !include config/covers.yaml
frontend:
  themes: !include_dir_merge_named ./themes
group: !include config/groups.yaml
homeassistant: !include config/home_assistant.yaml
input_boolean: !include config/input_booleans.yaml
# intent_script: !include_dir_named config/intent_scripts
logger: !include config/logger.yaml
lovelace:
  mode: yaml
media_player: !include config/media_players.yaml
panel_iframe: !include config/side_menu.yaml
scene: !include config/scenes.yaml
script: !include config/scripts.yaml
sensor: !include_dir_merge_list config/sensors
stream:
tts:
  - platform: google_translate
vacuum: !include config/vacuums.yaml
zone: !include config/zones.yaml
zwave: !include config/zwave.yaml

