default_config:

alexa:
  smart_home:

api:

automation: !include_dir_merge_list config/automations

device_tracker:
  - platform: tomato
    host: !secret ip_router
    username: !secret user_router
    password: !secret pass_router
    http_id: !secret extra_router_httpid

frontend:
  themes: !include_dir_merge_named ./themes

homeassistant:
  elevation: 195
  external_url: !secret url_external
  latitude: !secret lat_home
  longitude: !secret long_home
  name: Home
  packages: !include_dir_named ./config/packages
  time_zone: America/Chicago
  unit_system: imperial
  currency: USD
  country: US

input_boolean: !include config/input_booleans.yaml

intent_script: !include_dir_merge_named config/intent_scripts

logger: !include config/logger.yaml

logbook:
  exclude:
    entities:
      - automation.lights_poll_lamp

lovelace:
  mode: yaml
  resources: !include config/lovelace/resources.yaml
  # dashboards:
  #   lovelace-cast:
  #     mode: yaml
  #     title: Castable Dashboard
  #     filename: ./ui-lovelace.cast.yaml
  #     show_in_sidebar: true
  #     require_admin: true

panel_iframe: !include config/side_menu.yaml

scene: !include scenes.yaml

script: !include_dir_named config/scripts

sensor:
  - platform: template
    sensors: !include_dir_merge_named config/sensor_templates

# stream:
#   ll_hls: true
#   part_duration: 1 # Range of 0.2 to 1.5
#   segment_duration: 5 # Range of 2 to 10

# switch: !include config/switches.yaml

tts:
  - platform: google_translate

# vacuum: !include config/vacuums.yaml

weather:
  - platform: darksky
    api_key: !secret token_darksky
    mode: daily

zone: !include config/zones.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies: '172.18.0.0/24'

