default_config:

alexa:
  smart_home:
api:
automation: !include_dir_merge_list config/automations
camera: !include config/cameras.yaml
cast: !include config/cast.yaml
cover: !include config/covers.yaml
frontend:
  themes: !include_dir_merge_named ./themes
group: !include config/groups.yaml
homeassistant: !include config/homeassistant.yaml
input_boolean: !include config/input_booleans.yaml
intent_script: !include_dir_merge_named config/intent_scripts
logger: !include config/logger.yaml
lovelace:
  mode: yaml
media_player: !include config/media_players.yaml
panel_iframe: !include config/side_menu.yaml
scene: !include config/scenes.yaml
script: !include_dir_named config/scripts
sensor: 
  - platform: template
    sensors: !include_dir_merge_named config/sensor_templates
stream:
tts:
  - platform: google_translate
vacuum: !include config/vacuums.yaml
weather: !include config/weather.yaml
zone: !include config/zones.yaml
zwave: !include config/zwave.yaml
