###############################################################################################
## Cooling Sensors
########################################################################################

sensor:
  - platform: template
    sensors:
      # If cooling is active, then set to target temp, otherwise set to 0
      # This is for UI purposes
      hvac_track_cool:
        friendly_name: 'HVAC Tracking of Cooling'
        device_class: temperature
        unit_of_measurement: '°F'
        entity_id:
          - sensor.hvac_action
          - sensor.hvac_temp_target
          - climate.thermostat_mode
        value_template: >-
          {%- set isOperating = is_state('sensor.hvac_action', 'cooling') -%}
          {%- set tempValue = states('sensor.hvac_temp_target') if isOperating else 0 -%}
          {{tempValue}}

  # Cooling counts triggered for today
  - platform: history_stats
    name: hvac_count_cool_today
    entity_id: sensor.hvac_action
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
    state: cooling
    type: count

  # Cooling counts triggered since the filter was changed
  - platform: history_stats
    name: hvac_count_cool_sincechange
    entity_id: sensor.hvac_action
    start: "{{ as_timestamp(states('input_text.hvac_store_date_lastchange')) }}"
    end: '{{ now() }}'
    state: cooling
    type: count

  # TODO: Determine how to add a daily average

  # Cooling duration for today
  - platform: history_stats
    name: hvac_duration_cool_today
    entity_id: sensor.hvac_action
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
    state: cooling
    type: time

  # Cooling duration in last 24 hours
  - platform: history_stats
    name: hvac_duration_cool_last24hrs
    entity_id: sensor.hvac_action
    state: cooling
    end: '{{ now() }}'
    type: time
    duration:
      hours: 24

  # Cooling duration for last 7 days
  - platform: history_stats
    name:  hvac_duration_cool_last7days
    entity_id: sensor.hvac_action
    state: cooling
    end: '{{ now() }}'
    type: time
    duration:
      days: 7

  # Cooling duration since the filter was marked replaced
  - platform: history_stats
    name: hvac_duration_cool_sincechange
    entity_id: sensor.hvac_action
    start: "{{ as_timestamp(states('input_text.hvac_store_date_lastchange')) }}"
    end: '{{ now() }}'
    state: cooling
    type: time

###############################################################################################
## Customizations
########################################################################################

homeassistant:
  customize:
    sensor.hvac_count_cool_today:
      friendly_name: 'HVAC Trigger Counts (Cooling) - Today'
    sensor.hvac_count_cool_sincechange:
      friendly_name: 'HVAC Trigger Counts (Cooling) - Since Filter Changed'
    sensor.hvac_duration_cool_today:
      friendly_name: 'HVAC Duration (Cooling) - Today'
    sensor.hvac_duration_cool_last24hrs:
      friendly_name: 'HVAC Duration (Cooling) - Last 24 Hours'
    sensor.hvac_duration_cool_last7days:
      friendly_name: 'HVAC Duration (Cooling) - Last 7 Days'
    sensor.hvac_duration_cool_sincechange:
      friendly_name: 'HVAC Duration (Cooling) - Since Filter Changed'
