script:
  homeassistant_reload_all:
    alias: '_Lifecycle - Reload Home Assistant'
    description: 'Reloads all the internal domains (i.e., automations, persons, scripts, etc)'
    sequence:
      - service: system_log.write
        data:
          message: "Reloading Domains"
          level: info
      - service: automation.reload
      - service: frontend.reload_themes
      - service: group.reload
      - service: homeassistant.reload_core_config
      - service: input_boolean.reload
      - service: scene.reload