alias: 'Lights - Turn All OFF'
description: 'Turns off all the lights in the entire house'
sequence:
  - condition: template
    value_template: >
        {{ states.light | rejectattr('state', 'eq', 'off') | map(attribute='entity_id') | list | count > 0 }}
  - service: light.turn_off
    data_template:
      entity_id: >-
        {{ states.light | rejectattr('state', 'eq', 'off') | map(attribute='entity_id') | list | join(", ") }}