alias: 'Lights - Turn OFF Status Lights from Switches'
description: 'Make those blinding switch lights turn off'
sequence:
  - service: zwave.set_config_parameter
    data: { node_id: 2, parameter: 3, size: 1, value: 2 }
  - service: zwave.set_config_parameter
    data: { node_id: 3, parameter: 3, size: 1, value: 2 }
  - service: zwave.set_config_parameter
    data: { node_id: 4, parameter: 3, size: 1, value: 2 }
  - service: zwave.set_config_parameter
    data: { node_id: 5, parameter: 3, size: 1, value: 2 }
  - service: zwave.set_config_parameter
    data: { node_id: 6, parameter: 3, size: 1, value: 2 }
  - service: zwave.set_config_parameter
    data: { node_id: 7, parameter: 3, size: 1, value: 2 }
  - service: zwave.set_config_parameter
    data: { node_id: 8, parameter: 3, size: 1, value: 2 }
  - service: zwave.set_config_parameter
    data: { node_id: 9, parameter: 3, size: 1, value: 2 }
  - service: zwave.set_config_parameter
    data: { node_id: 10, parameter: 3, size: 1, value: 2 }
  - service: zwave.set_config_parameter
    data: { node_id: 11, parameter: 3, size: 1, value: 2 }
  - service: zwave.set_config_parameter
    data: { node_id: 12, parameter: 3, size: 1, value: 2 }
  - service: zwave.set_config_parameter
    data: { node_id: 13, parameter: 3, size: 1, value: 2 }
  - service: zwave.set_config_parameter
    data: { node_id: 15, parameter: 3, size: 1, value: 2 }