alias: 'Lights - Lamp Only'
description: 'Turns off all the lights in the entire house, EXCEPT Living Room Lamp'
sequence:
  - condition: template
    value_template: >
      {%- set excludes = ['light.lamp'] -%}
      {{ states.light | rejectattr('state', 'eq', 'off') | rejectattr('entity_id', 'in', excludes) | map(attribute='entity_id') | list | count > 0 }}
  - service: light.turn_off
    data_template:
      entity_id: >-
        {%- set excludes = ['light.lamp'] -%}
        {{ states.light | rejectattr('state', 'eq', 'off') | rejectattr('entity_id', 'in', excludes) | map(attribute='entity_id') | list | join(", ") }}
