alias: 'Movie Time'
sequence:
  - service: scene.create
    data:
      scene_id: before_lighting
      snapshot_entities: >
        {% set switches = states.switch | rejectattr('state', 'eq', 'unavailable') | map(attribute='entity_id') | list %}
        {% set lights = states.light | rejectattr('state', 'eq', 'unavailable') | map(attribute='entity_id') | list %}
        {{ switches + lights }}
  - service: scene.turn_on
    target:
      entity_id: scene.set_movie_time_lights
    data:
      transition: 8
