sequence:
  - service: notify.alexa_media_codex_s_echo_show
    data:
      message: 'Toggling Garage Door, waiting 3 minutes between'
      data:
        type: announce
  - service: cover.open_cover
    data:
      entity_id: cover.garage_door
  - delay: '00:03:00'
  - service: cover.close_cover
    data:
      entity_id: cover.garage_door
