sequence:
  - service: notify.alexa_media_living_room_show
    data:
      message: 'Toggling Garage Door, waiting 15 minutes between'
      data:
        type: announce
  - service: cover.open_cover
    entity_id: cover.garage_door
  - delay: '00:15:00'
  - service: notify.alexa_media_living_room_show
    data:
      message: '15 minutes has been met, closing now. It should be aerated!'
      data:
        type: announce
  - service: cover.close_cover
    entity_id: cover.garage_door
