- url: /community_plugin/custom-header/custom-header.js
  type: module
- url: /community_plugin/mini-media-player/mini-media-player-bundle.js
  type: module
- url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
  type: module
- url: /community_plugin/lovelace-auto-entities/auto-entities.js
  type: module
- url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
  type: module
- url: /community_plugin/bar-card/bar-card.js
  type: js
- url: /community_plugin/button-entity-row/button-entity-row.js
  type: module
- url: /community_plugin/secondaryinfo-entity-row/secondaryinfo-entity-row.js
  type: js
- url: /community_plugin/lovelace-card-tools/card-tools.js
  type: module
- url: /community_plugin/fan-control-entity-row/fan-control-entity-row.js
  type: js
- url: /community_plugin/lovelace-swipe-navigation/swipe-navigation.js
  type: js
- url: /community_plugin/lovelace-template-entity-row/template-entity-row.js
  type: module
- url: /community_plugin/lovelace-multiple-entity-row/multiple-entity-row.js
  type: module
- url: /community_plugin/weather-card/weather-card.js
  type: module
- url: /community_plugin/lovelace-card-mod/card-mod.js
  type: module
- url: /community_plugin/simple-thermostat/simple-thermostat.js
  type: module
- url: /community_plugin/lovelace-layout-card/layout-card.js
  type: module