type: 'custom:paper-buttons-row'
buttons:
  - icon: 'mdi:refresh'
    name: Reload All Things
    entity: script.homeassistant_reload_all
    style:
      button:
        background: '#999900'
        border-radius: 9999px
        color: lightgray
  - icon: 'mdi:refresh'
    name: Restart HA
    entity: homeassistant.restart
    style:
      button:
        background: '#CC0000'
        border-radius: 9999px
        color: lightgray
