- alias: 'AAA_HA Startup'
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: system_log.write
      data_template:
        message: "HA Started, Running Start Automation - {{ trigger }}"
        level: warning
    - delay: '00:00:30'
    - service: homeassistant.update_entity
      data:
        entity_id: sensor.hvac_count_avg_sincechange
