- alias: 'Entity Registry Updated (Create|Remove)'
  initial_state: true
  trigger:
    - platform: event
      event_type: entity_registry_updated
      event_data:
        action: create
    - platform: event
      event_type: entity_registry_updated
      event_data:
        action: remove
  action:
    - service: system_log.write
      data_template:
        message: "Entity Registry Updated Triggered - {{ trigger }}"
        level: warning
    - service: notify.alexa_media_everywhere
      data_template:
        message: >
          {% set status = "ADDED TO" if trigger.event.data.action != "remove" else "REMOVED FROM" %}
          {% set domain = trigger.event.data.entity_id.split('.')[0].replace('_', ' ') %}
          '<voice name="Matthew">An entity of type {{ domain }} has been {{ status }} the Entity Registry</voice>.'
        data:
          type: announce
          method: speak