# At night, LEDs on the switches are blindingly bright, so we mute them
- alias: 'Lights - Status LEDs OFF'
  initial_state: true
  trigger:
    platform: time
    at: "23:00:00"
  action:
    - service: script.lights_all_status_off

# In the morning, let's get the LEDs on the switches back on
- alias: 'Lights - Status LEDs ON'
  initial_state: true
  trigger:
    platform: time
    at: "06:00:00"
  action:
    - service: script.lights_all_status_on