- alias: 'Motion - (Announce) Front Doorbell Cam'
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.motion_front_doorbell_cam
  condition:
    condition: state
    entity_id: input_boolean.announce_level_info
    state: 'on'
  action:
    - service: notify.alexa_media_living_room_show
      data_template:
        message: >
          {%- set status = 'Started' if trigger.to_state.state != 'off' else 'Ended' -%}
          'Motion Detection {{ status }} at Front Door'
        data:
          type: tts