# At night, LEDs on the switches are blindingly bright, so we mute them
- alias: 'Switch Status LEDs OFF'
  initial_state: true
  trigger:
    platform: time
    at: "23:00:00"
  action:
    - service: script.turn_off_switch_status

# In the morning, let's get the LEDs on the switches back on
- alias: 'Switch Status LEDs ON'
  initial_state: true
  trigger:
    platform: time
    at: "06:00:00"
  action:
    - service: script.turn_on_switch_status