- alias: 'Util - Vacuum Docked'
  initial_state: true
  trigger:
    platform: state
    entity_id: vacuum.dusty
    to: 'docked'
  condition:
    condition: state
    entity_id: input_boolean.announce_level_info
    state: 'on'
  action:
    - service: notify.alexa_media_living_room_show
      data:
        message: 'Dusty has completed his task!'
        data:
          type: announce