- alias: 'Webhook - Cam Motion - Set - Front Door'
  trigger:
    platform: webhook
    webhook_id: cam_motion_front_door_set
  action:
    - service: system_log.write
      data_template:
        message: "Motion Webhook Triggered - {{ trigger }}"
        level: warning
    - entity_id: input_boolean.cam_motion_front_door
      service_template: >
        {% set service = 'turn_on' if trigger.query.on else 'turn_off' %}
        input_boolean.{{ service }}
