- alias: 'Webhook - Motion - Set - Front Doorbell Cam'
  trigger:
    platform: webhook
    webhook_id: motion_set_front_doorbell
  action:
    - service: system_log.write
      data_template:
        message: "Motion Webhook Triggered - {{ trigger }}"
        level: info
    - entity_id: input_boolean.motion_front_doorbell_cam
      service_template: >
        {% set service = 'turn_on' if trigger.query.on else 'turn_off' %}
        input_boolean.{{ service }}
