input_boolean:
  track_mini_heater:
    name: 'Tracker - Mini Heater'
    icon: 'mdi:go-kart-track'

automation:
  - alias: 'Mini Heater - Announce Bathroom is Warmed'
    initial_state: true
    trigger:
      - platform: state
        entity_id: switch.bathroom
        to: 'on'
        for: '00:07:00'
    condition:
      condition: state
      entity_id: input_boolean.track_mini_heater
      state: 'off'
    action:
      - service: notify.alexa_media_living_room_show
        data:
          message: 'Bathroom should be heated'
          data:
            type: tts

  - alias: 'Mini Heater - Auto Shutoff'
    initial_state: true
    trigger:
      - platform: state
        entity_id: switch.bathroom
        to: 'on'
        for: '00:25:00'
    condition:
      condition: state
      entity_id: input_boolean.track_mini_heater
      state: 'off'
    action:
      - service: switch.turn_off
        entity_id: switch.bathroom

  - alias: 'Mini Heater - Announce Tracking Status'
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_boolean.track_mini_heater
    action:
      - service: notify.alexa_media_living_room_show
        data_template:
          message: >
            {%- set status = 'now tracking the main heater' if trigger.to_state.state == 'on' else 'in manual mode' -%}
            'Mini Heater is {{ status }}'
          data:
            type: tts

  - alias: 'Mini Heater - Track Main Heater'
    initial_state: true
    trigger:
      - platform: state
        entity_id: climate.thermostat_mode
        attribute: hvac_action
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: climate.thermostat_mode
          state: 'heat'
        - condition: state
          entity_id: input_boolean.track_mini_heater
          state: 'on'
    action:
      - entity_id: switch.bathroom
        service: >
          {% set service = 'turn_on' if 'heating' == trigger.to_state.attributes.hvac_action else 'turn_off' %}
          switch.{{ service }}
      - condition: state
        entity_id: input_boolean.announce_level_info
        state: 'on'
      - service: notify.alexa_media_living_room_show
        data_template:
          message: >
            {%- set status = trigger.to_state.attributes.hvac_action -%}
            'Mini Heater is now {{ status }}'
          data:
            type: tts

