input_button:
  rapid_toggle_switch:
    name: 'Rapid Toggle Switch'
    icon: 'mdi:flash-alert'

automation:
  - alias: 'Rapid Toggle Switch'
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_button.rapid_toggle_switch
    # condition:
    #   condition: state
    #   entity_id: switch.pink_light
    #   state: 'on'
    action:
      - repeat:
          count: 5
          sequence:
            - service: switch.turn_off
              entity_id: switch.pink_light
            - delay: 
                milliseconds: 250
            - service: switch.turn_on
              entity_id: switch.pink_light
            - delay: 
                milliseconds: 1000