automation:
  - alias: 'Announce Tracking Status - Soldering Iron'
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_boolean.track_solder_iron
    action:
      - service: notify.alexa_media_living_room_show
        data_template:
          message: >
            {%- set status = 'Initialized' if trigger.to_state.state == 'on' else 'Uninitialized' -%}
            'Tracking {{ status }} for Soldering Iron'
          data:
            type: tts

  - alias: 'Mini Heater - Auto Shutoff'
    initial_state: true
    condition:
      condition: state
      entity_id: input_boolean.track_solder_iron
      state: 'on'
    trigger:
      - platform: state
        entity_id: switch.kasa_wifi_outlet
        to: 'on'
        for: '00:15:00'
    action:
      # Announce Turning Off
      - service: notify.alexa_media_living_room_show
        data:
          message: 'Automatically turning off soldering iron'
          data:
            type: tts
      - service: switch.turn_off
        entity_id: switch.kasa_wifi_outlet

