# https://github.com/openhab/org.openhab.binding.zwave/blob/master/doc/kwikset/smartcode888_0_0.md
- platform: template
  sensors:
    lock_front_door_battery:
      friendly_name: 'Front Door Lock Battery'
      value_template: '{{ states.zwave.front_door_lock.attributes.battery_level }}'
      unit_of_measurement: '%'
      entity_id: zwave.front_door_lock
    lock_front_door_status: 
      friendly_name: 'Front Door Lock Status'
      value_template: '{{ states.lock.front_door_lock_locked.attributes.lock_status }}'
      entity_id: lock.front_door_lock_locked