- platform: template
  sensors:
    thermostat_target:
      friendly_name: "Thermostat Target Temperature"
      value_template: "{{state_attr('climate.thermostat_mode', 'temperature')}}"
      device_class: temperature
      unit_of_measurement: "°F"
