- platform: template
  sensors:
    outside_temp:
      friendly_name: "Outside Temperature"
      value_template: "{{state_attr('weather.home', 'temperature')}}"
      device_class: temperature
      unit_of_measurement: "°F"
