####################
# 60 min History

- type: 'custom:mini-graph-card'
  align_state: right
  animate: true
  hours_to_show: 1
  line_width: 2
  name: Thermostat (60min)
  points_per_hour: 120
  update_interval: 15
  show:
    icon: false
    fill: true
  entities:
    - entity: sensor.thermostat_temp
      name: Read Temp
      show_fill: true
    - entity: sensor.hvac_temp_target
      name: Target Temp
      show_fill: false
    - entity: sensor.outside_temp
      name: Outside Temp
      show_fill: false
    - entity: sensor.hvac_track_heat
      color: "#880000"
      name: Heating
      show_fill: true
      show_legend: false
      smoothing: false
    - entity: sensor.hvac_track_cool
      color: "#000055"
      name: Cooling
      show_fill: true
      show_legend: false
      smoothing: false

####################
# 90 min History

- type: 'custom:mini-graph-card'
  align_state: right
  animate: true
  hours_to_show: 1.75
  line_width: 2
  name: Thermostat (90min)
  points_per_hour: 60
  update_interval: 15
  show:
    icon: false
  entities:
    - entity: sensor.thermostat_temp
      name: Read Temp
      show_fill: true
      show_legend: false
    - entity: sensor.hvac_temp_target
      name: Target Temp
      show_fill: false
      show_legend: false
    - entity: sensor.outside_temp
      name: Outside Temp
      show_fill: false
      show_legend: false
    - entity: sensor.hvac_track_heat
      color: "#880000"
      name: Heating
      show_fill: true
      show_legend: false
      smoothing: false
    - entity: sensor.hvac_track_cool
      color: "#000055"
      name: Cooling
      show_fill: true
      show_legend: false
      smoothing: false