####################
# 12 Hour History

- type: 'custom:mini-graph-card'
  align_state: right
  animate: true
  hours_to_show: 12
  icon: 'mdi:thermometer-lines'
  line_width: 2
  name: Thermostat (12hrs)
  points_per_hour: 30
  update_interval: 3600
  show:
    icon: false
    legend: false
  entities:
    - entity: sensor.thermostat_temp
      name: Read Temp
      show_fill: true
    - entity: sensor.hvac_temp_target
      name: Target Temp
      show_fill: false
    - entity: sensor.outside_temp
      name: Outside Temp
      show_fill: false
    - entity: sensor.hvac_track_heat
      color: "#880000"
      name: Heating
      show_fill: true
      show_legend: false
      smoothing: false
    - entity: sensor.hvac_track_cool
      color: "#000055"
      name: Cooling
      show_fill: true
      show_legend: false
      smoothing: false

####################
# 24 Hour History

- type: 'custom:mini-graph-card'
  align_state: right
  animate: true
  hours_to_show: 24
  icon: 'mdi:thermometer-lines'
  line_width: 2
  name: Thermostat (24hrs)
  points_per_hour: 30
  update_interval: 3600
  show:
    icon: false
    legend: false
  entities:
    - entity: sensor.thermostat_temp
      name: Read Temp
      show_fill: true
    - entity: sensor.hvac_temp_target
      name: Target Temp
      show_fill: false
    - entity: sensor.outside_temp
      name: Outside Temp
      show_fill: false
    - entity: sensor.hvac_track_heat
      color: "#880000"
      name: Heating
      show_fill: true
      show_legend: false
      smoothing: false
    - entity: sensor.hvac_track_cool
      color: "#000055"
      name: Cooling
      show_fill: true
      show_legend: false
      smoothing: false