name: Home
latitude: !secret lat_home
longitude: !secret long_home
elevation: 195
unit_system: imperial
time_zone: America/Los_Angeles
# auth_providers:
#   - type: homeassistant
#   - type: trusted_networks
#     trusted_networks:
#       - 192.168.1.0/24
#       - 172.0.0.0/8
# customize: !include customize.yaml