motion_front_doorbell_cam:
  name: 'Motion - Front Doorbell Cam'
  icon: 'mdi:eye-circle'

announce_level_info:
  name: 'Announce - Info Level'
  icon: 'mdi:bullhorn-outline'

track_mini_heater:
  name: 'Tracker - Mini Heater'
  icon: 'mdi:go-kart-track'

track_solder_iron:
  name: 'Tracker - Soldering Iron'
  icon: 'mdi:firewire'
