presence_codex:
  name: 'Presence - Codex Rollup'
  initial: 'on'

presence_frecs:
  name: 'Presence - Frecs Rollup'
  initial: 'on'

motion_front_doorbell_cam:
  name: 'Motion - Front Doorbell Cam'
  initial: 'off'
  icon: 'mdi:eye-circle'

