motion_front_doorbell_cam:
  name: 'Motion - Front Doorbell Cam'
  icon: 'mdi:eye-circle'

announce_level_info:
  name: 'Announce - Info Level'
  icon: 'mdi:bullhorn-outline'

miniheat_track_heater:
  name: 'Mini Heater - Tracker'
  icon: 'mdi:go-kart-track'
