presence_codex:
  name: 'Presence - Codex Rollup'
  initial: 'on'

presence_frecs:
  name: 'Presence - Frecs Rollup'
  initial: 'on'

cam_motion_front_door:
  name: 'Front Door Cam Motion'
  initial: 'off'
  icon: 'mdi:eye-circle'