# https://www.home-assistant.io/integrations/logger/

# Reduced Logging
default: warning
logs:
  homeassistant.core: error
  homeassistant.components.websocket_api: error
  homeassistant.components.recorder: error
  pymyq: error
  kasa.protocols: error
  androidtv.androidtv.androidtv_async: error
  adb_shell.adb_device_async: error
  homeassistant.components.webhook: debug
#
#
# Enhanced Logging
# default: warning
# logs:
#   homeassistant.components: debug
