default: warn
# logs:
#   zwave_js_server: debug
# homeassistant.components.device_tracker: debug
# homeassistant.components.http: debug
# homeassistant.components.zwave: debug
# openzwave: debug
