turn_off_all_lights:
  alias: 'Turn off all lights'
  description: 'Turns off all the lights in the entire house'
  sequence:
    - service: light.turn_off
      entity_id: all
turn_on_all_lights:
  alias: 'Turn on all lights'
  description: 'Turns on all the lights in the entire house'
  sequence:
    - service: light.turn_on
      entity_id: all
