reload_all_domains:
  alias: 'Reload All Domains'
  description: 'Reloads all the internal domains (i.e., automations, persons, scripts, etc)'
  sequence:
    - service: system_log.write
      data:
        message: "Reloading Domains"
        level: info
    - service: automation.reload
    - service: frontend.reload_themes
    - service: group.reload
    - service: homeassistant.reload_core_config
    - service: input_boolean.reload
    - service: scene.reload

only_lamp:
  alias: 'Only Lamp On'
  description: 'Turns off all the lights in the entire house, EXCEPT Living Room Lamp'
  sequence:
    - condition: template
      value_template: >
        {%- set excludes = ['light.lamp'] -%}
        {{ states.light | rejectattr('state', 'eq', 'off') | rejectattr('entity_id', 'in', excludes) | map(attribute='entity_id') | list | count > 0 }}
    - service: light.turn_off
      data_template:
        entity_id: >-
          {%- set excludes = ['light.lamp'] -%}
          {{ states.light | rejectattr('state', 'eq', 'off') | rejectattr('entity_id', 'in', excludes) | map(attribute='entity_id') | list | join(", ") }}

turn_off_all_lights:
  alias: 'Turn off all lights'
  description: 'Turns off all the lights in the entire house'
  sequence:
    - condition: template
      value_template: >
          {{ states.light | rejectattr('state', 'eq', 'off') | map(attribute='entity_id') | list | count > 0 }}
    - service: light.turn_off
      data_template:
        entity_id: >-
          {{ states.light | rejectattr('state', 'eq', 'off') | map(attribute='entity_id') | list | join(", ") }}

turn_on_all_lights:
  alias: 'Turn on all lights'
  description: 'Turns on all the lights in the entire house'
  sequence:
    - service: light.turn_on
      entity_id: all
