# node_red:
#   title: 'Node Red'
#   url: 'http://192.168.1.55:1880'
#   icon: 'mdi:resistor-nodes'
#   require_admin: true

grafana:
  title: 'NFGArmy Metrics'
  url: 'https://grafana.nfgarmy.com/d/000000127/telegraf-system-dashboard?orgId=1&refresh=5s&kiosk'
  icon: 'mdi:chart-bar'
  require_admin: true

motioneye:
  title: 'Motion Eye'
  url: 'https://motioneye.nfgarmy.com'
  icon: 'mdi:camera-iris'
  require_admin: true
