- name: Home
  latitude: !secret lat_home
  longitude: !secret long_home
  radius: 150
  icon: mdi:castle

- name: 'HEB North'
  latitude: !secret lat_hebnorth
  longitude: !secret long_hebnorth
  radius: 175
  icon: mdi:cart

- name: 'Old House'
  latitude: !secret lat_oldhouse
  longitude: !secret long_oldhouse
  radius: 150
  icon: mdi:home-floor-negative-1