sensor:
  - platform: template
    sensors:
      ####################
      # Presence & Stats

      # Sensor to track battery level of phone
      presence_battery_phone_codex:
        friendly_name: 'Display Value for Phone Battery, for Codex'
        value_template: "{{ state_attr('device_tracker.phone_codex', 'battery_level') }}"
        unit_of_measurement: "%"

automation:
  # Detect Presence of Codex
  #  Currently only uses mobile app, but can/will expand for reliability
  - alias: 'Presence - Codex Detected'
    initial_state: true
    trigger:
      - platform: state
        entity_id: device_tracker.phone_codex
        to: 'home'
        for:
          minutes: 5
      - platform: state
        entity_id: device_tracker.phone_codex
        from: 'home'
    action:
      - service: system_log.write
        data_template:
          message: "Presence Change for Codex Triggered - {{ trigger }}"
          level: info
      - entity_id: input_boolean.presence_codex
        service_template : >-
          {%- set service = 'turn_on' if trigger.to_state.state == 'home' else 'turn_off' -%}
          input_boolean.{{ service }}