homeassistant:
  customize:
    device_tracker.phone_codex:
      entity_picture: '/local/people/detected_codex.png'

input_boolean:
  presence_codex:
    name: 'Presence - Codex Rollup'
    initial: true

sensor:
  - platform: template
    sensors:
      ####################
      # Presence & Stats

      # Sensor to track battery level of phone
      presence_battery_phone_codex:
        friendly_name: 'Presence - Phone Battery, for Codex'
        value_template: "{{ state_attr('device_tracker.phone_codex', 'battery_level') }}"
        unit_of_measurement: '%'

automation:
  # Detect Presence of Codex
  #  Currently only uses mobile app, but can/will expand for reliability
  - alias: 'Presence - Codex Detected'
    initial_state: true
    trigger:
      - platform: state
        entity_id: device_tracker.phone_codex
        to: 'home'
        for:
          minutes: 5
      - platform: state
        entity_id: device_tracker.phone_codex
        to: 'not_home'
        for:
          minutes: 5
    action:
      - service: system_log.write
        data_template:
          message: 'Presence Change for Codex Triggered - {{ trigger }}'
          level: info
      - entity_id: input_boolean.presence_codex
        service: >-
          {%- set serviceName = 'turn_on' if trigger.to_state.state == 'home' else 'turn_off' -%}
          input_boolean.{{ serviceName }}

