type: vertical-stack
title: Fans
cards:
  - type: 'custom:auto-entities'
    card:
      type: custom:layout-card
    filter:
      include:
        - domain: fan
          options:
            type: tile
            features:
              - type: "fan-speed"
    sort:
      method: state
      reverse: true
