####################
# Front Door Operations

type: vertical-stack
title: Front Door
cards:
  # Doorbell Cam
  - type: picture-entity
    aspect_ratio: 50%
    camera_image: camera.front_door
    entity: camera.front_door
    show_state: false
    hold_action:
      action: navigate
      navigation_path: !secret url_motioneye

  # Motion Detection Last Updated
  - type: entities
    entities:
      # Motion Detected Status
      - type: custom:template-entity-row
        entity: input_boolean.cam_motion_front_door
        icon: mdi:eye
        name: "Motion was last detected:"
        secondary: >
          {%- macro formatvalue(name, value, sep='') -%}
            {%- set name = '{}s'.format(name) if value > 1 else name -%}
            {{ '{} {}{}'.format(value, name, sep) if value >= 1 else '' }}
          {%- endmacro -%}

          {%- macro buildTimestamp(timeStamp) -%}
            {%- set time = ((as_timestamp(now()) - as_timestamp(timeStamp))) -%}
            {%- set seconds = formatvalue('second', ((time % 3600) % 60) | round(0), '') -%}
            {%- set minutes = formatvalue('minute', ((time % 3600) // 60) | int, '') -%}
            {%- set hours = formatvalue('hour', ((time % 86400) // 3600) | int, ', ') -%}
            {%- set days = formatvalue('day', (time // 86400) | int, ', ') -%}
            {{ 'Just now' if time < 1 else days + hours + minutes + seconds + ' ago' }}
          {%- endmacro -%}

          {{ buildTimestamp(states.input_boolean.cam_motion_front_door.last_changed) }}
        state: "{% if is_state('input_boolean.cam_motion_front_door', 'on')%} Detected {% else %} Idle {% endif %}"
        active: "{{ is_state('input_boolean.cam_motion_front_door', 'on') }}"
        tap_action:
          action: more-info

      # Lock Status / Actions
      - entity: lock.lock_front_door_status