####################
# Lighting UI

type: vertical-stack
title: Lighting Control
cards:
  ####################
  # Lighting Buttons

  - type: 'custom:paper-buttons-row'
    buttons:
      - icon: 'mdi:lamp'
        name: Lamp Only
        entity: script.lights_lamp_only
        style:
          button:
            box-shadow: '0px 1px 0px 0px #fff6af'
            background: 'linear-gradient(to bottom, #ffec64 5%, #ffab23 100%)'
            background-color: '#ffec64'
            border-radius: '6px'
            border: '1px solid #ffaa22'
            display: 'inline-block'
            cursor: 'pointer'
            color: '#333333'
            font-family: 'Arial'
            font-size: '15px'
            font-weight: 'bold'
            text-decoration: 'none'
            text-shadow: '0px 1px 0px #ffee66'
            text-align: 'center'
            width: '120px'
      - icon: 'mdi:lightbulb-off'
        name: All Off
        entity: script.lights_all_off
        style:
          button:
            box-shadow: '0px 1px 0px 0px #3d4285'
            background: 'linear-gradient(to bottom, #4E5396 5%, #3d4285 100%)'
            background-color: '#ffec64'
            border-radius: '6px'
            border: '1px solid #5F64A7'
            display: 'inline-block'
            cursor: 'pointer'
            color: '#AAA'
            font-family: 'Arial'
            font-size: '15px'
            font-weight: 'bold'
            text-decoration: 'none'
            text-shadow: '0px 1px 0px #4E5396'
            text-align: 'center'
            width: '120px'
      - icon: 'mdi:lightbulb-on'
        name: All On
        entity: script.lights_all_on
        style:
          button:
            box-shadow: '0px 1px 0px 0px #3d4285'
            background: 'linear-gradient(to bottom, #4E5396 5%, #3d4285 100%)'
            background-color: '#ffec64'
            border-radius: '6px'
            border: '1px solid #5F64A7'
            display: 'inline-block'
            cursor: 'pointer'
            color: '#AAA'
            font-family: 'Arial'
            font-size: '15px'
            font-weight: 'bold'
            text-decoration: 'none'
            text-shadow: '0px 1px 0px #4E5396'
            text-align: 'center'
            width: '120px'

  ####################
  # Lighting Controls
  #
  # Tap-able icons, slider rows
  # Entities are automatic via `auto-entities`
  # "ON" states rise to the top!

  - type: entities
    title: Lights
    entities:
      - type: custom:auto-entities
        card:
          type: custom:fold-entity-row
          head:
            type: section
            label: Show More
        filter:
          exclude:
            - entity_id: /.*(alexa|echo|shuffle|repeat|disturb).*/
          include:
            - domain: light
              options:
                type: 'custom:slider-entity-row'
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
        sort:
          method: state
          reverse: true

  - type: entities
    title: Switches
    entities:
      - type: custom:auto-entities
        card:
          type: custom:fold-entity-row
          head:
            type: section
            label: Show More
        filter:
          exclude:
            - entity_id: /.*(alexa|echo|shuffle|repeat|disturb).*/
          include:
            - domain: switch
              options:
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
        sort:
          method: state
          reverse: true

