####################
# Lighting UI

type: vertical-stack
title: Lighting
cards:

  ####################
  # Lighting Buttons

  - type: 'custom:button-entity-row'
    buttons:
      - icon: 'mdi:lamp'
        name: Lamp Only
        service: script.only_lamp
        style:
            box-shadow: "0px 1px 0px 0px #fff6af"
            background: "linear-gradient(to bottom, #ffec64 5%, #ffab23 100%)"
            background-color: "#ffec64"
            border-radius: "6px"
            border: "1px solid #ffaa22"
            display: "inline-block"
            cursor: "pointer"
            color: "#333333"
            font-family: "Arial"
            font-size: "15px"
            font-weight: "bold"
            padding: "6px 24px"
            text-decoration: "none"
            text-shadow: "0px 1px 0px #ffee66"
      - icon: 'mdi:lightbulb-off'
        name: All Off
        service: script.turn_off_all_lights
        style:
            box-shadow: "0px 1px 0px 0px #3d4285"
            background: "linear-gradient(to bottom, #4E5396 5%, #3d4285 100%)"
            background-color: "#ffec64"
            border-radius: "6px"
            border: "1px solid #5F64A7"
            display: "inline-block"
            cursor: "pointer"
            color: "#AAA"
            font-family: "Arial"
            font-size: "15px"
            font-weight: "bold"
            padding: "6px 24px"
            text-decoration: "none"
            text-shadow: "0px 1px 0px #4E5396"

  ####################
  # Lighting Controls
  #
  # Tap-able icons, slider rows
  # Entities are automatic via `auto-entities`
  # "ON" states rise to the top!

  - type: 'custom:auto-entities'
    card:
      show_header_toggle: false
      type: entities
    filter:
      exclude:
        - entity_id: /.*(alexa|echo|shuffle|repeat|disturb).*/
      include:
        - domain: light
          options:
            type: 'custom:slider-entity-row'
            tap_action:
              action: toggle
            hold_action:
              action: more-info
        - domain: switch
          options:
            tap_action:
              action: toggle
            hold_action:
              action: more-info
    sort:
      method: state
      reverse: true