####################
# Misc Utilities for the home

type: vertical-stack
title: Misc Utils

cards:
- type: entities
  show_header_toggle: false
  entities:
    # Garage Door
    - type: 'custom:secondaryinfo-entity-row'
      entity: cover.garage_door
      secondary_info: '<span style="text-transform: capitalize;">[[ if("undefined" != {entity}.state, {entity}.state, "") ]]</span>'

    # Robo Vac
    - type: 'custom:secondaryinfo-entity-row'
      entity: vacuum.dusty
      secondary_info: >-
        <span style="text-transform: capitalize;">
          [[ if(vacuum.dusty.attributes.error == "undefined", "", vacuum.dusty.attributes.error) ]]
        </span>

    # Robo Vac Controls
    - type: 'custom:button-entity-row'
      buttons:
        - icon: 'mdi:play'
          service: vacuum.start
          service_data:
            entity_id: vacuum.dusty
          style:
            - color: white
        - icon: 'mdi:pause'
          service: vacuum.pause
          service_data:
            entity_id: vacuum.dusty
          style:
            - color: white
        - icon: 'mdi:stop'
          service: vacuum.stop
          service_data:
            entity_id: vacuum.dusty
          style:
            - color: white
        - icon: 'mdi:map-marker'
          service: vacuum.locate
          service_data:
            entity_id: vacuum.dusty
          style:
            - color: white
        - icon: 'mdi:home'
          service: vacuum.return_to_base
          service_data:
            entity_id: vacuum.dusty
          style:
            - color: white