####################
# Home Tab

- title: Home
  path: home
  icon: "mdi:home"

  cards:
    - !include ../templates/home/front_door.yaml

    - type: vertical-stack
      title: Overview
      cards:
        - type: glance
          entities:
            - entity: sun.sun
            - entity: input_boolean.motion_front_doorbell_cam
            - entity: person.codex
            - entity: person.freckles
            - entity: binary_sensor.docker_hub_update_available
            - entity: input_boolean.track_mini_heater
              tap_action:
                action: toggle
            - entity: input_button.rapid_toggle_switch
              tap_action:
                action: press
            - entity: switch.jerky_maker
              tap_action:
                action: none
            - entity: switch.bathroom
              tap_action:
                action: toggle
            - entity: switch.christmas_lights
              tap_action:
                action: toggle

    - !include ../templates/home/fans.yaml

    - !include ../templates/home/lighting.yaml

    - type: vertical-stack
      title: Weather
      cards:
        - type: custom:weather-card
          entity: weather.forecast_home
          forecast: true

    - !include ../templates/home/misc_utils.yaml
