####################
# Home Tab

- title: Home
  path: home
  icon: 'mdi:home'

  cards:
    - !include ../templates/home/front_door.yaml

    - type: vertical-stack
      title: Overview
      cards:
        - type: glance
          entities:
            - entity: sun.sun
            - entity: input_boolean.cam_motion_front_door
            - entity: person.codex
            - entity: person.freckills
            - entity: binary_sensor.updater

    - !include ../templates/home/fans.yaml

    - !include ../templates/home/lighting.yaml

    - type: vertical-stack
      title: Weather
      cards:
        - type: custom:weather-card
          entity: weather.dark_sky
          forecast: true

    - !include ../templates/home/misc_utils.yaml