- title: Home
  path: home
  icon: 'mdi:home'
  cards:
    - type: vertical-stack
      title: Front Door
      cards:
      - type: picture-entity
        aspect_ratio: 50%
        camera_image: camera.front_door
        entity: camera.front_door
        show_state: false
        hold_action:
          action: navigate
          navigation_path: !secret url_motioneye
      - type: entities
        entities:
          - type: custom:template-entity-row
            entity: input_boolean.cam_motion_front_door
            icon: mdi:eye
            name: "Motion was last detected:"
            secondary: >
              {%- macro formatvalue(name, value, sep='') %}
                {%- set name = '{}s'.format(name) if value > 1 else name %}
                {{ '{} {}{}'.format(value, name, sep) if value >= 1 else '' }}
              {%- endmacro %}

              {%- macro buildTimestamp(timeStamp) %}
                {%- set time = ((as_timestamp(now()) - as_timestamp(timeStamp))) %}
                {%- set seconds = formatvalue('second', ((time % 3600) % 60) | round(0), '') %}
                {%- set minutes = formatvalue('minute', ((time % 3600) // 60) | int, '') %}
                {%- set hours = formatvalue('hour', ((time % 86400) // 3600) | int, ', ') %}
                {%- set days = formatvalue('day', (time // 86400) | int, ', ') %}
                {{ 'Just now' if time < 1 else days + hours + minutes + seconds + ' ago' }}
              {%- endmacro %}

              {{ buildTimestamp(states.input_boolean.cam_motion_front_door.last_changed) }}
            state: "{% if is_state('input_boolean.cam_motion_front_door', 'on')%} Detected {% else %} Idle {% endif %}"
            active: "{{ is_state('input_boolean.cam_motion_front_door', 'on') }}"
            tap_action:
              action: more-info
      - type: entities
        title: Lock
        show_header_toggle: false
        entities:
          - entity: lock.lock_front_door_status
    - type: vertical-stack
      title: Overview
      cards:
        - type: glance
          entities:
            - entity: sun.sun
            - entity: input_boolean.cam_motion_front_door
            - entity: person.codex
            - entity: person.freckills
            - entity: binary_sensor.updater
    - type: vertical-stack
      title: Fans
      cards:
        - type: 'custom:auto-entities'
          card:
            show_header_toggle: false
            type: entities
          filter:
            include:
              - domain: fan
                options:
                  type: 'custom:fan-control-entity-row'
          sort:
            method: state
            reverse: true
    - type: vertical-stack
      title: Lighting
      cards:
      - type: 'custom:button-entity-row'
        buttons:
          - icon: 'mdi:lamp'
            name: Lamp Only
            service: script.only_lamp
            style:
                box-shadow: "0px 1px 0px 0px #fff6af"
                background: "linear-gradient(to bottom, #ffec64 5%, #ffab23 100%)"
                background-color: "#ffec64"
                border-radius: "6px"
                border: "1px solid #ffaa22"
                display: "inline-block"
                cursor: "pointer"
                color: "#333333"
                font-family: "Arial"
                font-size: "15px"
                font-weight: "bold"
                padding: "6px 24px"
                text-decoration: "none"
                text-shadow: "0px 1px 0px #ffee66"
          - icon: 'mdi:lightbulb-off'
            name: All Off
            service: script.turn_off_all_lights
            style:
                box-shadow: "0px 1px 0px 0px #3d4285"
                background: "linear-gradient(to bottom, #4E5396 5%, #3d4285 100%)"
                background-color: "#ffec64"
                border-radius: "6px"
                border: "1px solid #5F64A7"
                display: "inline-block"
                cursor: "pointer"
                color: "#AAA"
                font-family: "Arial"
                font-size: "15px"
                font-weight: "bold"
                padding: "6px 24px"
                text-decoration: "none"
                text-shadow: "0px 1px 0px #4E5396"
      - type: 'custom:auto-entities'
        card:
          show_header_toggle: false
          type: entities
        filter:
          exclude:
            - entity_id: /.*(alexa|echo|shuffle|repeat|disturb).*/
          include:
            - domain: light
              options:
                hold_action:
                  action: more-info
                tap_action:
                  action: toggle
                type: 'custom:slider-entity-row'
            - domain: switch
        sort:
          method: state
          reverse: true


    - type: vertical-stack
      title: Weather
      cards:
        - type: custom:weather-card
          entity: weather.dark_sky
          forecast: true

    - type: vertical-stack
      title: Misc Utils
      cards:
        - type: entities
          show_header_toggle: false
          entities:
            - type: 'custom:secondaryinfo-entity-row'
              entity: cover.garage_door
              secondary_info: '<span style="text-transform: capitalize;">[[ if("undefined" != {entity}.state, {entity}.state, "") ]]</span>'
            - type: 'custom:secondaryinfo-entity-row'
              entity: vacuum.dusty
              secondary_info: >-
                <span style="text-transform: capitalize;">
                  [[ if(vacuum.dusty.attributes.error == "undefined", "", vacuum.dusty.attributes.error) ]]
                </span>
            - type: 'custom:button-entity-row'
              buttons:
                - icon: 'mdi:play'
                  service: vacuum.start
                  service_data:
                    entity_id: vacuum.dusty
                  style:
                    - color: white
                - icon: 'mdi:pause'
                  service: vacuum.pause
                  service_data:
                    entity_id: vacuum.dusty
                  style:
                    - color: white
                - icon: 'mdi:stop'
                  service: vacuum.stop
                  service_data:
                    entity_id: vacuum.dusty
                  style:
                    - color: white
                - icon: 'mdi:map-marker'
                  service: vacuum.locate
                  service_data:
                    entity_id: vacuum.dusty
                  style:
                    - color: white
                - icon: 'mdi:home'
                  service: vacuum.return_to_base
                  service_data:
                    entity_id: vacuum.dusty
                  style:
                    - color: white