- title: Utilities
  path: utilities
  icon: 'mdi:flash'
  badges: []
  cards:
    - type: vertical-stack
      title: Thermostat
      cards:
        - type: thermostat
          entity: climate.thermostat_mode
        - type: 'custom:bar-card'
          title: Internal Humidity
          entities:
            - sensor.thermostat_humidity
    - type: vertical-stack
      title: Thermostat History (90min)
      cards:
        - align_state: right
          animate: true
          entities:
            - entity: sensor.thermostat_temp
              name: Read Temp
              show_fill: true
            - entity: sensor.thermostat_target
              name: Target Temp
              show_fill: false
            - entity: sensor.outside_temp
              name: Outside Temp
              show_fill: false
          hours_to_show: 1.75
          name: Thermostat (90min)
          points_per_hour: 10
          show:
            icon: false
          type: 'custom:mini-graph-card'
          update_interval: 60
    - type: vertical-stack
      title: Thermostat History
      cards:
        - align_state: right
          animate: true
          entities:
            - entity: sensor.thermostat_temp
              name: Read Temp
              show_fill: true
            - entity: sensor.thermostat_target
              name: Target Temp
              show_fill: false
            - entity: sensor.outside_temp
              name: Outside Temp
              show_fill: false
          hours_to_show: 12
          icon: 'mdi:thermometer-lines'
          name: Thermostat (12hrs)
          points_per_hour: 4
          show:
            icon: false
            legend: false
          type: 'custom:mini-graph-card'
          update_interval: 3600
        - align_state: right
          animate: true
          entities:
            - entity: sensor.thermostat_temp
              name: Read Temp
              show_fill: true
            - entity: sensor.thermostat_target
              name: Target Temp
              show_fill: false
            - entity: sensor.outside_temp
              name: Outside Temp
              show_fill: false
          hours_to_show: 24
          icon: 'mdi:thermometer-lines'
          name: Thermostat (24hrs)
          points_per_hour: 2
          show:
            icon: false
            legend: false
          type: 'custom:mini-graph-card'
          update_interval: 3600
    - type: entities
      title: Misc Utils
      show_header_toggle: false
      entities:
        - type: 'custom:secondaryinfo-entity-row'
          entity: cover.garage_door
          secondary_info: '<span style="text-transform: capitalize;">[[ {entity}.state ]]</span>'
        - type: 'custom:secondaryinfo-entity-row'
          entity: vacuum.dusty
          secondary_info: '<span style="text-transform: capitalize;">[[ {entity}.attributes.error ]]</span>'
        - buttons:
            - icon: 'mdi:play'
              service: vacuum.start
              service_data:
                entity_id: vacuum.dusty
              style:
                - color: white
            - icon: 'mdi:pause'
              service: vacuum.pause
              service_data:
                entity_id: vacuum.dusty
              style:
                - color: white
            - icon: 'mdi:stop'
              service: vacuum.stop
              service_data:
                entity_id: vacuum.dusty
              style:
                - color: white
            - icon: 'mdi:map-marker'
              service: vacuum.locate
              service_data:
                entity_id: vacuum.dusty
              style:
                - color: white
            - icon: 'mdi:home'
              service: vacuum.return_to_base
              service_data:
                entity_id: vacuum.dusty
              style:
                - color: white
          type: 'custom:button-entity-row'
