####################
# Thermostat Tab

- title: Thermostat
  path: thermostat
  icon: 'mdi:thermometer-lines'

  cards:
    - type: vertical-stack
      title: Thermostat
      cards:
        - !include ../templates/thermostat/control.yaml
        - !include ../templates/thermostat/specs.yaml

    - type: vertical-stack
      title: Thermostat History (Recent)
      cards: !include ../templates/thermostat/history_recent.yaml

    - type: vertical-stack
      title: Thermostat History
      cards: !include ../templates/thermostat/history_longer.yaml
