- title: Thermostat
  path: thermostat
  icon: 'mdi:thermometer-lines'
  badges: []
  cards:
    - type: vertical-stack
      title: Thermostat
      cards:
        - type: thermostat
          entity: climate.thermostat_mode
        - type: 'custom:bar-card'
          title: Internal Humidity
          entities:
            - sensor.thermostat_humidity
        - type: entities
          entities:
            - sensor.
    - type: vertical-stack
      title: Thermostat History (Recent)
      cards:
        - type: 'custom:mini-graph-card'
          align_state: right
          animate: true
          hours_to_show: 1
          name: Thermostat (60min)
          points_per_hour: 120
          update_interval: 0.25
          show:
            icon: false
            fill: true
          entities:
            - entity: sensor.thermostat_temp
              name: Read Temp
              show_fill: true
            - entity: sensor.thermostat_target
              name: Target Temp
              show_fill: false
            - entity: sensor.outside_temp
              name: Outside Temp
              show_fill: false
            - entity: sensor.thermostat_track_heat
              color: "#880000"
              name: Heating
              show_fill: true
              show_legend: false
              smoothing: false
            - entity: sensor.thermostat_track_cool
              color: "#000055"
              name: Cooling
              show_fill: true
              show_legend: false
              smoothing: false
        - type: 'custom:mini-graph-card'
          align_state: right
          animate: true
          hours_to_show: 1.75
          name: Thermostat (90min)
          points_per_hour: 60
          update_interval: 60
          show:
            icon: false
          entities:
            - entity: sensor.thermostat_temp
              name: Read Temp
              show_fill: true
              show_legend: false
            - entity: sensor.thermostat_target
              name: Target Temp
              show_fill: false
              show_legend: false
            - entity: sensor.outside_temp
              name: Outside Temp
              show_fill: false
              show_legend: false
            - entity: sensor.thermostat_track_heat
              color: "#880000"
              name: Heating
              show_fill: true
              show_legend: false
              smoothing: false
            - entity: sensor.thermostat_track_cool
              color: "#000055"
              name: Cooling
              show_fill: true
              show_legend: false
              smoothing: false
    - type: vertical-stack
      title: Thermostat History
      cards:
        - type: 'custom:mini-graph-card'
          align_state: right
          animate: true
          hours_to_show: 12
          icon: 'mdi:thermometer-lines'
          name: Thermostat (12hrs)
          points_per_hour: 4
          update_interval: 3600
          show:
            icon: false
            legend: false
          entities:
            - entity: sensor.thermostat_temp
              name: Read Temp
              show_fill: true
            - entity: sensor.thermostat_target
              name: Target Temp
              show_fill: false
            - entity: sensor.outside_temp
              name: Outside Temp
              show_fill: false
            - entity: sensor.thermostat_track_heat
              color: "#880000"
              name: Heating
              show_fill: true
              show_legend: false
              smoothing: false
            - entity: sensor.thermostat_track_cool
              color: "#000055"
              name: Cooling
              show_fill: true
              show_legend: false
              smoothing: false
        - type: 'custom:mini-graph-card'
          align_state: right
          animate: true
          hours_to_show: 24
          icon: 'mdi:thermometer-lines'
          name: Thermostat (24hrs)
          points_per_hour: 2
          update_interval: 3600
          show:
            icon: false
            legend: false
          entities:
            - entity: sensor.thermostat_temp
              name: Read Temp
              show_fill: true
            - entity: sensor.thermostat_target
              name: Target Temp
              show_fill: false
            - entity: sensor.outside_temp
              name: Outside Temp
              show_fill: false
            - entity: sensor.thermostat_track_heat
              color: "#880000"
              name: Heating
              show_fill: true
              show_legend: false
              smoothing: false
            - entity: sensor.thermostat_track_cool
              color: "#000055"
              name: Cooling
              show_fill: true
              show_legend: false
              smoothing: false