####################
# Presence Tab

- title: Presence
  path: presence
  icon: 'mdi:tooltip-account'

  cards:
    - type: vertical-stack
      cards:
        - type: horizontal-stack
          cards:
            - !include ../templates/presence/codex.yaml
            - !include ../templates/presence/frecs.yaml

    ###############
    # Map Tracker
    ###############
    - type: custom:mod-card
      card:
        type: custom:auto-entities
        card:
          type: map
          default_zoom: 10
        filter:
          include:
            - domain: device_tracker
            - domain: zone
      # style:
      #   'hui-map-card': 
      #     $: |
      #       ha-card {
      #         max-height: 200px;
      #       }
      
