- title: System
  path: system
  icon: 'mdi:file-settings-variant-outline'
  badges: []
  cards:
    - entity: alarm_control_panel.alexa_guard_3b269
      type: alarm-panel
    - type: vertical-stack
      title: 'Battery Levels'
      cards:
        - type: 'custom:auto-entities'
          card:
            type: custom:bar-card
            align: left
            unit_of_measurement: "%"
            title_style:
              font-size: 16px
              padding: 10px
            value_style:
              font-size: 32px
              opacity: 0.85
              padding-left: 10px
            severity:
              - value: 50
                color: '#bf4040'
              - value: 75
                color: '#bf9540'
              - value: 100
                color: '#40bf40'
          filter:
            include:
              # - entity_id: '*battery*'
              - attributes:
                  battery_level: <=100
                options:
                  attribute: battery_level
            exclude:
              - domain: device_tracker
          sort:
            method: attribute
            attribute: battery_level
    - !include ../templates/shared/refresh.yaml
    - type: 'custom:auto-entities'
      card:
        show_header_toggle: false
        title: Scripts
        type: entities
      filter:
        include:
          - domain: script
      sort:
        method: name
    - type: 'custom:auto-entities'
      card:
        show_header_toggle: false
        title: Automations
        type: entities
      filter:
        include:
          - domain: automation
      sort:
        method: name
