- title: Devices
  path: devices
  icon: 'mdi:devices'
  badges: []
  cards:
    - type: 'custom:auto-entities'
      card:
        type: entities
        title: 'Presence Crap'
      filter:
        include:
          - entity_id: '*presence*'
    - type: 'custom:auto-entities'
      card:
        type: entities
        title: 'Input Booleans'
      filter:
        include:
          - domain: 'input_boolean'
    - type: 'custom:auto-entities'
      card:
        show_header_toggle: false
        title: 'Unavailable Entities'
        type: entities
      filter:
        include:
          - state: "unavailable"
      sort:
        method: name