- title: Devices
  path: devices
  icon: 'mdi:devices'
  badges: []
  cards:
    - type: entities
      title: Presence Crap
      entities:
        - type: custom:auto-entities
          card:
            type: custom:fold-entity-row
            head:
              type: section
              label: Show More
          filter:
            include:
              - entity_id: '*presence*'
    - !include ../templates/shared/refresh.yaml
    - type: entities
      title: Input Booleans
      entities:
        - type: custom:auto-entities
          card:
            type: custom:fold-entity-row
            head:
              type: section
              label: Show More
          filter:
            include:
              - domain: 'input_boolean'
    - type: entities
      title: Unavailable Entities
      entities:
        - type: custom:auto-entities
          card:
            type: custom:fold-entity-row
            head:
              type: section
              label: Show More
          filter:
            include:
              - state: "unavailable"
          sort:
            method: name