motion_front_doorbell_cam_lastseen:
  friendly_name: "Motion - Front Doorbell Cam (Last Seen)"
  value_template: >
    {%- macro formatvalue(name, value, sep='') -%}
      {%- set name = '{}s'.format(name) if value > 1 else name -%}
      {{ '{} {}{}'.format(value, name, sep) if value >= 1 else '' }}
    {%- endmacro -%}

    {%- macro buildTimestamp(timeStamp) -%}
      {%- set time = ((as_timestamp(now()) - as_timestamp(timeStamp))) -%}
      {%- set seconds = formatvalue('second', ((time % 3600) % 60) | round(0), '') -%}
      {%- set minutes = formatvalue('minute', ((time % 3600) // 60) | int, ', ') -%}
      {%- set hours = formatvalue('hour', ((time % 86400) // 3600) | int, ', ') -%}
      {%- set days = formatvalue('day', (time // 86400) | int, ', ') -%}
      {{ 'Just now' if time < 1 else days + hours + minutes + seconds + ' ago' }}
    {%- endmacro -%}

    {{ buildTimestamp(states.input_boolean.motion_front_doorbell_cam.last_changed) }}
