####################
# Presence & Stats

presence_battery_phone_codex:
  friendly_name: 'Display Value for Phone Battery, for Codex'
  value_template: "{{ state_attr('device_tracker.phone_codex', 'battery_level') }}"
  unit_of_measurement: "%"

presence_battery_phone_frecs:
  friendly_name: 'Display Value for Phone Battery, for Frecs'
  value_template: "{{ state_attr('device_tracker.phone_frecs', 'battery_level') }}"
  unit_of_measurement: "%"

####################
# Presence Consensus

# Determine State of Presence (empty|partial|majority|full)
#   This is accomplished by searching through all input_boolean's for `.presence_` in the Entity ID
#   and then compared for various requirements:
#     - If NO ONE is home, returns `empty` 
#     - If EVERYONE is home, returns `full` 
#     - If WINNING MAJORITY COUNT of people are home, returns `majority`
#     - If no other match is found, returns `partial` (ie, less than majority is home)
#
#   This sensor must be *manually* updated, since HA cannot auto-detect the effected entities
#       (see also: `automations/presence.yaml`, for the Automation aliased as 'Presence - Needs Consensus Update')

presence_consensus:
  friendly_name: 'Consensus state for presence in the house'
  value_template: >-
    {%- set ns = namespace(
      _states = states.input_boolean, 
      _contains = '\.presence_',
      entities = []
    ) -%}

    {%- for _ent in  ns._states -%}
      {% set ns.entities = ns.entities + [_ent] if (_ent | regex_search(ns._contains)) else ns.entities %}
    {%- endfor -%}
    {%- set entities_on = ns.entities | selectattr('state', 'eq', 'on') | map(attribute='entity_id') | list -%}
    {%- set count_total = ns.entities | count -%}
    {%- set count_on = entities_on | count -%}
    {%- set majority_home = count_on > count_on / 2 -%}
    {%- set full = count_on == count_total -%}
    
    {%- if 0 == count_on -%}
      empty
    {%- elif full -%}
      full
    {%- elif majority_home -%}
      majority
    {%- else -%}
      partial
    {%- endif -%}