###############################################################################################
## Inputs
########################################################################################

input_button:
  living_room_tv_select_hdmi1:
    name: 'Intent - (Trigger) Select HDMI 1'

###############################################################################################
## Automations
########################################################################################

automation:
  - alias: 'Intent - (Process) Select HDMI 1'
    initial_state: true
    trigger:
      platform: state
      entity_id: input_button.living_room_tv_select_hdmi1
    action:
      - service: script.select_hdmi_input
  - alias: 'Intent - (Process) Select HDMI 1 on Xbox Turn-On'
    initial_state: true
    trigger:
      platform: state
      entity_id: media_player.codexbox
      to: 'on'
    condition:
      condition: state
      entity_id: media_player.living_room_tv
      state: 'off'
    action:
      - service: script.select_hdmi_input
  - alias: 'Intent - Switch Back to Android'
    initial_state: true
    trigger:
      platform: state
      entity_id: media_player.codexbox
      to: 'off'
    action:
      # Switch TV back to Home when xbox goes off, but only if it's on
      - if:
          - alias: 'TV is on'
            condition: state
            entity_id: media_player.living_room_tv
            state: 'idle'
        then:
          - alias: 'Switch the TV to Home'
            service: androidtv.adb_command
            entity_id: media_player.living_room_tv
            data:
              command: 'HOME'
  - alias: 'Auto Turn Off XBOX'
    initial_state: true
    trigger:
      platform: state
      entity_id: media_player.living_room_tv
      to: 'off'
    condition:
      condition: state
      entity_id: media_player.codexbox
      state: 'on'
    action:
      - alias: 'Turn OFF the XBOX'
        service: media_player.turn_off
        entity_id: media_player.codexbox

###############################################################################################
## Scripts
########################################################################################

script:
  select_hdmi_input:
    alias: 'Intent - (Script) Select HDMI 1'
    sequence:
      - parallel:
          - sequence:
              # Turn on XBOX if it's off
              - alias: 'Turn on the XBOX'
                service: media_player.turn_on
                entity_id: media_player.codexbox
              - service: androidtv.adb_command
                data:
                  entity_id: media_player.living_room_tv
                  command: HOME
          # Turn on TV if it's off
          - if:
              - alias: "TV isn't on"
                condition: state
                entity_id: media_player.living_room_tv
                state: 'off'
            then:
              - alias: 'Turn on the TV'
                service: media_player.turn_on
                entity_id: media_player.living_room_tv

      # Press INPUT button 2x to move to HDMI1 selection,
      # and press Center button
      - service: androidtv.adb_command
        data:
          entity_id: media_player.living_room_tv
          command: INPUT
      - service: androidtv.adb_command
        data:
          entity_id: media_player.living_room_tv
          command: INPUT
      - service: androidtv.adb_command
        data:
          entity_id: media_player.living_room_tv
          command: CENTER

