###############################################################################################
## Inputs
########################################################################################

input_button:
  living_room_tv_select_hdmi1:
    name: 'Intent - (Trigger) Select HDMI 1'

###############################################################################################
## Automations
########################################################################################

automation:
  - alias: 'Intent - (Process) Select HDMI 1'
    initial_state: true
    trigger:
      platform: state
      entity_id: input_button.living_room_tv_select_hdmi1
    action:
      - service: script.select_hdmi_input
  - alias: 'Intent - (Process) Select HDMI 1 on Xbox Turn-On'
    initial_state: true
    trigger:
      platform: state
      entity_id: media_player.codexbox
      to: 'on'
    condition:
      condition: state
      entity_id: media_player.living_room_tv
      state: 'off'
    action:
      - service: script.select_hdmi_input
  - alias: 'Intent - Switch Back to Android'
    initial_state: true
    trigger:
      platform: state
      entity_id: media_player.codexbox
      to: 'off'
    action:
      # Switch TV back to Home when xbox goes off, but only if it's on
      - if:
          - alias: 'TV is on'
            condition: state
            entity_id: media_player.living_room_tv
            state: 'idle'
        then:
          - alias: 'Switch the TV to Home'
            service: androidtv.adb_command
            entity_id: media_player.living_room_tv
            data:
              command: 'HOME'
  - alias: 'Auto Turn Off XBOX'
    initial_state: true
    trigger:
      platform: state
      entity_id: media_player.living_room_tv
      to: 'off'
    condition:
      condition: state
      entity_id: media_player.codexbox
      state: 'on'
    action:
      - alias: 'Turn OFF the XBOX'
        service: media_player.turn_off
        entity_id: media_player.codexbox

###############################################################################################
## Scripts
########################################################################################

script:
  select_hdmi_input:
    alias: 'Intent - (Script) Select HDMI 1'
    sequence:
      - parallel:
          - sequence:
              - service: androidtv.adb_command
                data:
                  entity_id: media_player.living_room_tv
                  command: HOME
          # Turn on TV if it's off
          - if:
              - alias: 'Is TV is OFF?'
                condition: state
                entity_id: media_player.living_room_tv
                state: 'off'
            then:
              - alias: "It's off, turn the TV ON!"
                service: media_player.turn_on
                entity_id: media_player.living_room_tv

      # Press INPUT button 2x to move to HDMI1 selection,
      # and press Center button
      - service: androidtv.adb_command
        alias: 'Press INPUT Button'
        data:
          entity_id: media_player.living_room_tv
          command: INPUT
      # Move cursor to absolute top. Max is 7 menu items on the TV
      # and it doesn't loop around when we hit top, so let's just spam it 7x
      - alias: 'Press UP Button 7x'
        repeat:
          count: 7
          sequence:
            - service: androidtv.adb_command
              data:
                entity_id: media_player.living_room_tv
                command: UP
      # Move cursor to HDMI1 (assuming the 7 presses above worked!)
      - alias: 'Press DOWN Button 3x'
        repeat:
          count: 3
          sequence:
            - service: androidtv.adb_command
              data:
                entity_id: media_player.living_room_tv
                command: DOWN
      - service: androidtv.adb_command
        alias: 'Press CENTER Button'
        data:
          entity_id: media_player.living_room_tv
          command: CENTER
