###############################################################################################
## Inputs
########################################################################################

input_boolean:
  living_room_tv_select_hdmi1:
    name: 'Intent - (Trigger) Select HDMI 1'

###############################################################################################
## Automations
########################################################################################

automation:
  - alias: 'Intent - (Process) Select HDMI 1'
    initial_state: true
    trigger:
      platform: state
      entity_id: input_boolean.living_room_tv_select_hdmi1
      to: 'on'
    action:
      - service: script.select_xbox_input

###############################################################################################
## Scripts
########################################################################################

script:
  select_xbox_input:
    sequence:
      - service: androidtv.adb_command
        data:
          entity_id: media_player.living_room_tv
          command: INPUT
      - service: androidtv.adb_command
        data:
          entity_id: media_player.living_room_tv
          command: INPUT
      - service: androidtv.adb_command
        data:
          entity_id: media_player.living_room_tv
          command: CENTER
      - service: input_boolean.turn_off
        entity_id: input_boolean.living_room_tv_select_hdmi1
