script:
  lights_all_status_off:
    alias: 'Lights - Turn OFF Status Lights from Switches'
    description: 'Make those blinding switch lights turn off'
    sequence:
      - service: ZWAVE_JS.SET_CONFIG_PARAMETER
        target:
          entity_id: >-
            {{ states.light | map(attribute='entity_id') | list | join(", ") }}
        data:
          parameter: 3
          value: 2

  lights_all_status_on:
    alias: 'Lights - Turn ON Status Lights from Switches'
    description: 'Make those blinding switch lights turn on'
    sequence:
      - service: ZWAVE_JS.SET_CONFIG_PARAMETER
        target:
          entity_id: >-
            {{ states.light | map(attribute='entity_id') | list | join(", ") }}
        data:
          parameter: 3
          value: 0
