HARestartIntent:
  card:
    type: simple
    title: Restart the Butler
    content: Restarting My Brain!
  speech:
    text: !include ../_alexa_responses.yaml
  action:
    - service: system_log.write
      data:
        message: 'Alexa wants to restart HA'
        level: warning
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.lifecycle_restart
