RunScriptIntent:
  card:
    type: simple
    title: Run Script
    content: >-
      Asking Home Assistant to run script: {{ ScriptName | replace(" ", "_") }}
  action:
    service: script.turn_on
    data_template:
      entity_id: script.{{ ScriptName | replace(" ", "_") }}
  speech:
    type: plain
    text: !include ../_alexa_responses.yaml