# Lamp Switch doesn't update for some reason, we have to poll it like chumps

# automation:
#   - alias: 'Lights - Poll Lamp'
#     initial_state: true
#     trigger:
#       platform: time_pattern
#       seconds: /15
#     action:
#       - service: zwave_js.refresh_value
#         entity_id: light.lamp
